### PR TITLE
Added handler for exceptions from Reader's constructor

### PR DESCRIPTION
**Pull request by antishov**
Issue #70

### CODE REVIEW

**Comment by runk** [comment]
Thanks for PR. Any thoughts why travis failed on node 0.12?

**Comment by antishov** [comment]
I haven't got any ideas. In my local environment with node.js version 0.12.18 all tests are pass.

**Comment by antishov** [comment]
Ok, by this output:

> maxmind section: binary search tree should test everything: GeoIP2-Anonymous-IP-Test:
     TypeError: undefined is not a function
      at sprintf_format (node_modules/ip-address/node_modules/sprintf-js/src/sprintf.js:134:70)
      at sprintf (node_modules/ip-address/node_modules/sprintf-js/src/sprintf.js:26:16)
      at Address4.toGroup6 (node_modules/ip-address/lib/ipv4.js:161:15)
      at Address6.parse4in6 (node_modules/ip-address/lib/ipv6.js:563:39)
      at Address6.parse (node_modules/ip-address/lib/ipv6.js:573:18)
      at new Address6 (node_modules/ip-address/lib/ipv6.js:92:29)
      at tester (test/e2e.js:128:18)
      at Context.<anonymous> (test/e2e.js:141:9)

I see, that problem is inside sprintf-js (depended by ip-address) module. Can you re-run Travis, maybe problem will be solved by repeated installation of npm modules?

**Comment by aahoughton** [comment]
any update here?  considering pulling this library, but I just *know* someone on my end is going to Do The Wrong Thing, and I'd like the additional safety.

**Comment by aahoughton** [comment]
Thank you!

**Pull request closed without merging**
