### PR TITLE
Add default response type to Reader and remove interface prefixing

### LINKED ISSUE #125: Breaking changes in minor version for typings
Hey, I noticed my build failing after I updated this package to 2.9.

It would be great if you only released major versions when breaking changes were introduced.

I also noticed you started prefixing all interfaces with `I`, please see https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#names
The TS team strongly suggests that you don't do that.

### PR DESCRIPTION
**Pull request by kevcenteno**
**Breaking changes** (for typescript users)

Fixes #125, in particular removes interface prefixing
Also a bit of cleanup in response to https://github.com/runk/node-maxmind/pull/126

@omar84 Do you mind taking a look?

### CODE REVIEW

**Comment by omar84** [comment]
@kevcenteno thanks for adding a response that specifies which generics are allowed, this is great.

but maybe we should just re-implement generics, and document it well in the readme.

if you wanna replace the last bit of the index.d.ts file with this: 

```
export class Reader<T extends Response> {
  public metadata: Metadata;
  public get: (ipAddress: string) => T | null;
  constructor(buffer: Buffer, opts?: OpenOpts);
}

export type openCb<T> = (err: Error, cb: Reader<T>) => void;

export function open<T>(filepath: string, opts?: OpenOpts | openCb<T>, cb?: openCb<T>): void;

export function openSync<T>(filepath: string, opts?: OpenOpts): Reader<T>;

export function validate(ipAddress: string): boolean;
```

and maybe we should update the readme to include some typescript examples, I have some here:

```typescript
import * as maxmind from 'maxmind';

maxmind.open<ICityResponse>('/path/to/GeoLite2-City.mmdb', (err, cityLookup) => {
  let city: ICityResponse = cityLookup.get('66.6.44.4');
});


// sync version

let cityLookup = maxmind.openSync<ICityResponse>('/path/to/GeoLite2-City.mmdb');
let city: ICityResponse = cityLookup.get('66.6.44.4'); // response of type ICityResponse


// use Reader class directly

let buffer: Buffer = downloadFileToStream(someCloudBlob);
let cityLookup = new maxmind.Reader<ICityResponse>(buffer);
```

**Comment by omar84** [comment]
@kevcenteno thanks for adding a response that specifies which generics are allowed, this is great.

maybe we should update the readme to include some typescript examples, I have some here:

```typescript
import * as maxmind from 'maxmind';

maxmind.open<maxmind.CityResponse>('/path/to/GeoLite2-City.mmdb', (err, cityLookup) => {
  let city: maxmind.CityResponse = cityLookup.get('66.6.44.4');
});


// sync version

let cityLookup = maxmind.openSync<maxmind.CityResponse>('/path/to/GeoLite2-City.mmdb');
let city: maxmind.CityResponse = cityLookup.get('66.6.44.4'); 


// use Reader class directly

let buffer: Buffer = downloadFileToStream(someCloudBlob);
let cityLookup = new maxmind.Reader<maxmind.CityResponse>(buffer);
```

**Comment by kevcenteno** [comment]
Thank you @omar84!  I've updated the Readme

**Comment by omar84** [comment]
@runk can you please merge this? thanks

**Pull request merged**
