### PR TITLE
Maxmind Express/Session/Middleware Example

### PR DESCRIPTION
**Pull request by knoxcard**
Maxmind Session Example - people have been thanking me all over the internet when I share this golden piece of code.  Should be right in in the intro of the README doc.

### CODE REVIEW

**Comment by runk** [comment]
Feels like it'd better be placed under examples directory (currently doesn't exist) and we refer to those examples in readme. Thoughts?

**Comment by knoxcard** [comment]
An examples folder would be great.  Maybe just a one line reference in the README?  Something like, remember to run MaxMind once per user, per session.  Refer to the examples folder for full code to use with Express.

**Comment by knoxcard** [comment]
The words sessions and middleware are what is lacking in the README documentation.  Not sure how to create a folder on here, just using Github.  If you create that, I can add the file?

**Comment by runk** [comment]
https://github.com/runk/node-maxmind/tree/master/examples

**Comment by knoxcard** [comment]
Thanks! Added first example.

**Pull request closed without merging**
