### PR TITLE
Make internal methods private

### PR DESCRIPTION
**Pull request by oschwald**

### CODE REVIEW

**Comment by runk** [comment]
LGTM. Would you mind resolving the conflict please?

**Comment by runk** [comment]
Also, if you'd follow semantic release commit semantics, your changes would go out automatically: https://github.com/semantic-release/semantic-release

**Comment by oschwald** [comment]
I am happy to follow the commit messages enforced by that module, but they obviously include some value judgments. For instance, this is technically a breaking change as it makes something that was public private. However, I don't believe these methods were ever advertised and aren't particularly useful for anything but internal use. Should I categorize this as a breaking change that will necessitate a major version bump?

**Comment by runk** [comment]
Yeah, technically it's a breaking change if someone consumed those methods under the hood.

**Comment by oschwald** [comment]
OK, I updated the commit message to use the format described by that module and to mark it as a breaking change.

**Pull request merged**
